### ISSUE TITLE
Does ParamTools Parameters class inflation index parameter values?

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/ParamTools#34]
@hdoupe,  I've been looking more at the ParamTools repository since your talk on Monday.  I see that you have, in addition to the weather and baseball examples, a taxcalc example.  Does that mean that the ParamTools Parameters class does inflation indexing of the parameters?  If not, then don't you think this is a misleading example of what ParamTools can do?  For me as a potential user of ParamTools, I would prefer to see a shorter simulation-model-parameter example, like an example showing how the ParamTools.Parameters class would handle the three (non-inflation-indexed) parameters used by the Behavioral-Responses `response` function.

**Comment by hdoupe** [comment]
Hi @martinholmer, thanks for taking a look at ParamTools and giving me some feedback. I wrote ParamTools with the goal of being general enough for all types of model parameters while still being able to achieve Taxcalc parameter processing and validation functionality. So, I think it makes a lot of sense to include that example in the repo. Further, the taxcalc parameters showcase ParamTools key features in a very nice way, and they have a real world application with the taxcalc package. For these reasons, I plan to make the taxcalc example to be the first one that is shown in the docs.

ParamTools does not have the ability to inflate parameters. However, the `Parameters` class could be extended to apply some type of indexing rules to parameters. In my opinion, parameter indexing is out of ParamTools' scope right now. I would very much like to write up an example demonstrating how one could extend ParamTools to index parameters to inflation. I may convert the code used in that example to a new "ParamTools-Indexing" package so that projects that rely on indexing can easily use ParamTools.

I do like your idea of including an example using the parameters from your Behavior-Responses package. I will add that to the repo in the coming days. Thanks again for your feedback.
